### ISSUE TITLE
Use with top-level objects in string variables not supported?

### ISSUE THREAD

**Issue by jonahe** [maffoo/jsonquote#6]
Hi. First: really nice library! Thanks!

I have a use case where I have a javascript object as a String
 `val myString = s"""{a: 1, b: "hello"}""" `

which I would then want to use with your library to get a `play.api.libs.json.JsObject`  like so:
 `val jsObj = json"$myString"`

But I can't get this to work. Every way I try I get back a `play.api.libs.json.JsString`. Do you know of a workaround for this?

**Comment by maffoo** [comment]
If you have a string containing actual json, you can just use the standard play-json mechanism to parse it:
```scala
scala> play.api.libs.json.Json.parse("""{"a": 1, "b": "hello"}""")
res6: play.api.libs.json.JsValue = {"a":1,"b":"hello"}
```

If you want to use the modified syntax supported by jsonquote like leaving out quotes around object keys, you can call the jsonquote parsing function directly:
```scala
scala> net.maffoo.jsonquote.play.Parse(Seq("""{a: 1, b: "hello"}"""))
res6: play.api.libs.json.JsValue = {"a":1,"b":"hello"}
```

But in general I wouldn't recommend doing this. The point of jsonquote is to use the macro system to do the parsing of json string literals at compile time, and because of the compile-time safety this gives, you can get away with having the modified syntax. If you are parsing json at runtime, you probably want to use valid json, if you're parsing json from some API call, for example, so the standard parsing capabilities built into play-json would be better.

**Comment by jonahe** [comment]
Thanks a lot for the quick reply! The Parse method was exactly what I needed. I'm parsing a javascript text response from a (bad) api. The strings I'm planning to use this on are valid javascript objects, so given that your library is ok with javascript object -> json, it should be safe enough.
